import "./globals.css";
import Provider from "./component/Provider";
import { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Umur Deniz Dikmen-Dev Portfolio",
  description: "Generated by create next app",
};

export type ChildrenType = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: ChildrenType) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👋</text></svg>"
        />
      </head>
      <body className="dark:bg-stone-900">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
